### ISSUE TITLE
Warning: file_get_contents()

### ISSUE THREAD

**Issue by jasperjorna** [esclkm/debugbar#5]
Getting these 2 warnings:

Warning: file_get_contents() [<a href='function.file-get-contents'>function.file-get-contents</a>]: php_network_getaddresses: getaddrinfo failed: Name or service not known in /plugins/debugbar/debugbar.footer.php on line 74

Warning: file_get_contents(http://home.dev/cotonti/testbench/?tpl_debug=1) [<a href='function.file-get-contents'>function.file-get-contents</a>]: failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known in /var/www/cotonti/testbench/plugins/debugbar/debugbar.footer.php on line 74

PHP 5.3.10

Awesome plugin, BTW!

**Comment by esclkm** [comment]
some hostings are block external downoloading /// set @
